server:
  port: 8080

spring:
  application:
    name: Reggie_take_out
  datasource:
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_reggie?characterEncoding=utf-8&characterSetResults=utf8
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: is_delete
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    在映射实体或者属性时，将数据库表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

reggie:
  path: D:\ProgrammingProject\IdeaProject2022\springboot_heima_02\Reggie_take_out\src\main\resources\img\