server:
  port: 8080

spring:
  application:
    name: Reggie_take_out
  datasource:
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_reggie?characterEncoding=utf-8&characterSetResults=utf8
    username: root
    password: 123456
  #Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0   #默认操作 0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4   #连接池中最大空闲连接
        min-idle: 0   #连接池最小空闲连接
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: is_delete
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    在映射实体或者属性时，将数据库表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

reggie:
  path: D:\ProgrammingProject\IdeaProject2022\springboot_heima_02\Reggie_take_out\src\main\resources\img\
